### ISSUE TITLE
Aktualizacja strony www

### ISSUE THREAD

**Issue by Kika-hash** [Kika-hash-org/Mickiewicz#10]
- [x] Sklonuj repozytorium: https://github.com/Kika-hash-org/Mickiewicz 
- [x] W dowolnym miejscu (header / body / stopka) dodaj poniższą informację:
- Nasze koło zostało objęte Patronatem Honorowym przez firmę programistyczną ALAN Systems z Rybnika
- [x] By informacja była bardziej atrakcyjna, dodaj również grafikę: logo firmy ALAN Systems (dostępne na stronie: https://alan-systems.com/pl/ )

**Comment by MaeMil76** [comment]
zrobilem
